### ISSUE TITLE
Compile fails on XCode 8.2.1 on El Capitan through Carthage

### ISSUE THREAD

**Issue by olvb** [kean/RxNuke#1]
> The following build commands failed:
> 	CompileSwift normal arm64 /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift
> 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> (2 failures)
> /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift:70:49: error: same-type requirement makes generic parameter 'Trait' non-generic
> /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift:70:81: error: same-type requirement makes generic parameter 'Element' non-generic
> /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift:78:36: error: use of undeclared type 'Element'
> /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift:78:36: error: use of undeclared type 'Element'
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/RxNuke/RxNuke.xcodeproj -scheme "RxNuke iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal arm64 /Users/.../Carthage/Checkouts/RxNuke/Source/RxNuke.swift
> 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> (2 failures)

XCode 8.2.1 (latest version available on El Capitan 10.11.6)

**Comment by kean** [comment]
Hey!

It compiles on the latest Xcode 8.3.3 with a latest Swift 3.1.

The culprit is this line:

```swift
extension RxSwift.PrimitiveSequence where Trait == RxSwift.SingleTrait, Element == Nuke.Image
```

It uses feature introduced in Swift 3.1 (the Swift version mentioned in README in requirements seems to be wrong):

> * [SR-1009](https://bugs.swift.org/browse/SR-1009):
>
> Constrained extensions allow same-type constraints between generic parameters and concrete types. This enables you to create extensions, for example, on `Array` with `Int` elements:
>
>   ```swift
>  extension Array where Element == Int { }
 > ```

Is there a chance that you could update to Swift 3.1? As an alternative, I think I could make this code work on the previous Swift versions.

**Comment by olvb** [comment]
Not immediately as I'm stuck with XCode 8.2 on El Capitan, but I plan to switch to Sierra in the next weeks and I am in no hurry so don't go trough the trouble. You might want to specify which swift 3.1 is expected in the requirements, though :)
Again, thank you for your swiftness

**Comment by kean** [comment]
It's Xcode 9 already, RxNuke migrated to Swift 4, going to close this.
